package com.spirit.koil.api.model.reasoning;

import java.util.Locale;
import java.util.regex.Pattern;

/**
 * Validator for direct conversational responses.
 *
 * <p>This class never authors user-facing assistant text. Even trivial greetings,
 * acknowledgements, and thanks are generated by the active model. The guard only
 * rejects obvious runtime/control-metadata drift when that material was not requested.</p>
 */
public final class DirectResponseIntentGuard {

    private static final Pattern INTERNAL_METADATA = Pattern.compile(
            "\\b(?:model\\s+family|provider|quantization|backend|runtime\\s+metadata|tool\\s+registry|system\\s+prompt|system\\s+message|developer\\s+message|control\\s+context|prompt\\s+contract|llama\\.?cpp|colibri|qwen|granite|mistral|gemma|parameter\\s+count|gpu\\s+layers?)\\b"
    );
    private static final Pattern INTERNAL_REQUEST = Pattern.compile(
            "\\b(?:model\\s+family|what\\s+model|which\\s+model|provider|quantization|backend|runtime|system\\s+prompt|system\\s+message|tool\\s+registry|prompt\\s+contract|llama\\.?cpp|colibri|gpu\\s+layers?)\\b"
    );

    private DirectResponseIntentGuard() {
    }

    /**
     * Rejects obvious control/runtime drift when the user did not request it.
     * This is intentionally narrow: it is not a general semantic judge and it
     * does not block legitimate answers about models when the user asked for
     * that information.
     */
    public static Validation validateDirectAnswer(String prompt, String response) {
        String request = normalize(prompt);
        String answer = normalize(response);
        if (answer.isBlank()) return Validation.accept();
        if (INTERNAL_REQUEST.matcher(request).find()) return Validation.accept();
        if (INTERNAL_METADATA.matcher(answer).find()) {
            return Validation.reject(
                    "The response drifted into unrequested Koil/model runtime metadata instead of answering the latest user request."
            );
        }
        return Validation.accept();
    }

    public static String correctionDirective(String prompt) {
        return "Answer only the latest user request: \"" + compact(prompt, 240) + "\". "
                + "Do not discuss Model's family, provider, backend, quantization, runtime metadata, system/control prompts, "
                + "tool registry, or implementation details unless the user explicitly asked about them. "
                + "Do not explain this correction. Return only the relevant user-facing answer.";
    }

    private static String normalize(String value) {
        return value == null ? "" : value.toLowerCase(Locale.ROOT)
                .replace('\r', ' ').replace('\n', ' ').replaceAll("\\s+", " ").strip();
    }

    private static String compact(String value, int maximum) {
        String cleaned = value == null ? "" : value.replaceAll("\\s+", " ").strip();
        if (cleaned.length() <= maximum) return cleaned;
        return cleaned.substring(0, Math.max(0, maximum - 3)) + "...";
    }


    public record Validation(boolean valid, String detail) {
        public Validation {
            detail = detail == null ? "" : detail.strip();
        }

        public static Validation accept() {
            return new Validation(true, "");
        }

        public static Validation reject(String detail) {
            return new Validation(false, detail);
        }
    }
}
