package com.spirit.koil.api.model.tool;

import com.google.gson.*;
import com.spirit.koil.api.automation.capability.AutomationToolCoordinator;
import com.spirit.koil.api.model.*;

import java.time.Duration;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicInteger;

/** Compiled reusable tool workflows plus non-blocking interval/deadline scheduling. */
public final class BackgroundAutomationModelToolRegistry {
    public static final String WORKFLOW_DEFINE="workflow.define", WORKFLOW_RUN="workflow.run", WORKFLOW_LIST="workflow.list", WORKFLOW_DELETE="workflow.delete";
    public static final String SCHEDULE_CREATE="scheduler.create", SCHEDULE_STATUS="scheduler.status", SCHEDULE_LIST="scheduler.list", SCHEDULE_CANCEL="scheduler.cancel";
    private static final ConcurrentHashMap<String,Workflow> WORKFLOWS=new ConcurrentHashMap<>();
    private static final ConcurrentHashMap<String,Job> JOBS=new ConcurrentHashMap<>();
    private static final ScheduledExecutorService SCHEDULER=Executors.newScheduledThreadPool(2,r->{Thread t=new Thread(r,"Koil-Background-Automation");t.setDaemon(true);return t;});
    private static final List<ModelToolDefinition> DEFINITIONS=definitions();
    private BackgroundAutomationModelToolRegistry(){}
    public static String version(){return "background-automation-tools-v1";}
    public static List<ModelToolDefinition> modelTools(){return DEFINITIONS;}
    public static boolean supports(String id){return Set.of(WORKFLOW_DEFINE,WORKFLOW_RUN,WORKFLOW_LIST,WORKFLOW_DELETE,SCHEDULE_CREATE,SCHEDULE_STATUS,SCHEDULE_LIST,SCHEDULE_CANCEL).contains(id);}

    public static CompletableFuture<ModelToolResult> execute(UUID request,ModelToolCall call,boolean preapproved){
        if(call==null||!supports(call.toolId()))return CompletableFuture.completedFuture(failed(call,"unknown_background_tool","Unknown background automation capability."));
        try{
            return switch(call.toolId()){
                case WORKFLOW_LIST -> CompletableFuture.completedFuture(listWorkflows(call));
                case SCHEDULE_LIST -> CompletableFuture.completedFuture(listJobs(call));
                case SCHEDULE_STATUS -> CompletableFuture.completedFuture(status(call));
                case WORKFLOW_DEFINE -> CompletableFuture.completedFuture(define(call));
                case WORKFLOW_DELETE -> CompletableFuture.completedFuture(delete(call));
                case SCHEDULE_CANCEL -> CompletableFuture.completedFuture(cancel(call));
                case WORKFLOW_RUN -> ModelToolApproval.require(request,call,preapproved,"Run workflow",string(call.arguments(),"workflowId","")).thenCompose(ok->ok?runNow(call):CompletableFuture.completedFuture(failed(call,"approval_required","Workflow execution was not approved.")));
                case SCHEDULE_CREATE -> ModelToolApproval.require(request,call,preapproved,"Schedule background workflow",scheduleDetail(call)).thenApply(ok->ok?schedule(call):failed(call,"approval_required","Background scheduling was not approved."));
                default -> CompletableFuture.completedFuture(failed(call,"unknown_background_tool","Unknown background automation capability."));
            };
        }catch(Exception e){return CompletableFuture.completedFuture(failed(call,"background_automation_failed",msg(e)));}
    }
    private static ModelToolResult define(ModelToolCall c){JsonObject a=args(c);String id=string(a,"workflowId","");if(id.isBlank())id="flow-"+UUID.randomUUID().toString().substring(0,10);JsonArray steps=a.has("steps")&&a.get("steps").isJsonArray()?a.getAsJsonArray("steps"):new JsonArray();if(steps.isEmpty())return failed(c,"empty_workflow","steps must contain at least one tool call.");if(steps.size()>32)return failed(c,"workflow_too_large","A workflow may contain at most 32 steps.");Workflow w=new Workflow(id,string(a,"description",""),steps.deepCopy(),System.currentTimeMillis());WORKFLOWS.put(id,w);JsonObject out=new JsonObject();out.addProperty("workflowId",id);out.addProperty("steps",steps.size());out.addProperty("compiled",true);return completed(c,out,"Stored compiled session workflow.");}
    private static CompletableFuture<ModelToolResult> runNow(ModelToolCall c){Workflow w=resolveWorkflow(args(c));if(w==null)return CompletableFuture.completedFuture(failed(c,"workflow_not_found","No matching workflow exists."));return executeWorkflow(w).thenApply(out->completed(c,out,"Workflow executed through registered Koil tools."));}
    private static ModelToolResult schedule(ModelToolCall c){JsonObject a=args(c);Workflow w=resolveWorkflow(a);if(w==null){if(a.has("steps")&&a.get("steps").isJsonArray()){String id="flow-inline-"+UUID.randomUUID().toString().substring(0,8);w=new Workflow(id,"inline scheduled workflow",a.getAsJsonArray("steps").deepCopy(),System.currentTimeMillis());WORKFLOWS.put(id,w);}else return failed(c,"workflow_not_found","Provide workflowId or inline steps.");}
        long delay=longVal(a,"delayMs",0,0,Duration.ofDays(7).toMillis());String timerId=string(a,"timerId","");if(!timerId.isBlank()){long r=AutomationTimerModelToolRegistry.remainingMillis(timerId);if(r<0)return failed(c,"timer_not_found","The referenced timer does not exist or is cancelled.");delay=r;}
        long interval=longVal(a,"intervalMs",0,0,Duration.ofDays(1).toMillis());int maxRuns=integer(a,"maxRuns",interval>0?Integer.MAX_VALUE:1,1,100000);String jobId="job-"+UUID.randomUUID().toString().substring(0,12);Job job=new Job(jobId,w.id,interval,maxRuns,System.currentTimeMillis()+delay);JOBS.put(jobId,job);Workflow finalW=w;Runnable task=()->runJob(job,finalW);ScheduledFuture<?> f=interval>0?SCHEDULER.scheduleAtFixedRate(task,delay,Math.max(100,interval),TimeUnit.MILLISECONDS):SCHEDULER.schedule(task,delay,TimeUnit.MILLISECONDS);job.future=f;JsonObject out=jobJson(job);out.addProperty("nonBlocking",true);return completed(c,out,"Scheduled workflow without keeping model inference alive.");}
    private static void runJob(Job job,Workflow w){if(job.cancelled||job.runs.get()>=job.maxRuns){cancelFuture(job);return;}job.running=true;job.lastStarted=System.currentTimeMillis();try{JsonObject out=executeWorkflow(w).get(30,TimeUnit.MINUTES);job.lastResult=out;job.lastError="";}catch(Exception e){job.lastError=msg(e);}finally{job.running=false;job.lastFinished=System.currentTimeMillis();int n=job.runs.incrementAndGet();if(job.intervalMs<=0||n>=job.maxRuns)cancelFuture(job);}}
    private static CompletableFuture<JsonObject> executeWorkflow(Workflow w){CompletableFuture<JsonObject> chain=CompletableFuture.completedFuture(new JsonObject());JsonObject state=new JsonObject();JsonArray results=new JsonArray();state.add("steps",results);for(JsonElement el:w.steps){if(!el.isJsonObject())continue;JsonObject step=el.getAsJsonObject();chain=chain.thenCompose(ignored->{if(!condition(step,state)){JsonObject skipped=new JsonObject();skipped.addProperty("stepId",string(step,"id","step"));skipped.addProperty("status","skipped");results.add(skipped);return CompletableFuture.completedFuture(state);}String toolId=string(step,"toolId","");if(toolId.isBlank()||supports(toolId)){JsonObject bad=new JsonObject();bad.addProperty("stepId",string(step,"id","step"));bad.addProperty("status","failed");bad.addProperty("error","Invalid or recursive background tool step.");results.add(bad);return CompletableFuture.completedFuture(state);}JsonObject toolArgs=step.has("arguments")&&step.get("arguments").isJsonObject()?step.getAsJsonObject("arguments").deepCopy():new JsonObject();ModelToolCall call=new ModelToolCall("bg-"+UUID.randomUUID(),toolId,toolArgs);return AutomationToolCoordinator.execute(null,call,true).thenApply(r->{JsonObject jr=new JsonObject();jr.addProperty("stepId",string(step,"id","step"));jr.addProperty("toolId",toolId);jr.addProperty("status",r.status());jr.add("output",r.output());if(!r.failureCode().isBlank())jr.addProperty("failureCode",r.failureCode());results.add(jr);state.add(string(step,"id","step"),jr);return state;});});}return chain;}
    private static boolean condition(JsonObject step,JsonObject state){if(!step.has("when")||!step.get("when").isJsonObject())return true;JsonObject w=step.getAsJsonObject("when");String sid=string(w,"stepId","");String path=string(w,"path","output");String op=string(w,"op","exists");JsonElement v=resolvePath(state.get(sid),path);JsonElement expected=w.get("value");return switch(op){case"exists"->v!=null&&!v.isJsonNull();case"eq"->Objects.equals(text(v),text(expected));case"ne"->!Objects.equals(text(v),text(expected));case"lt"->num(v)<num(expected);case"lte"->num(v)<=num(expected);case"gt"->num(v)>num(expected);case"gte"->num(v)>=num(expected);case"contains"->text(v).contains(text(expected));default->false;};}
    private static JsonElement resolvePath(JsonElement root,String path){JsonElement cur=root;for(String p:path.split("\\.")){if(p.isBlank())continue;if(cur==null||!cur.isJsonObject())return JsonNull.INSTANCE;cur=cur.getAsJsonObject().get(p);}return cur==null?JsonNull.INSTANCE:cur;}
    private static String text(JsonElement e){return e==null||e.isJsonNull()?"":e.isJsonPrimitive()?e.getAsString():e.toString();}private static double num(JsonElement e){try{return e==null?Double.NaN:e.getAsDouble();}catch(Exception x){return Double.NaN;}}
    private static ModelToolResult status(ModelToolCall c){Job j=JOBS.get(string(args(c),"jobId",""));return j==null?failed(c,"job_not_found","No matching scheduled job exists."):completed(c,jobJson(j),"Read scheduled job state.");}
    private static ModelToolResult listJobs(ModelToolCall c){JsonArray a=new JsonArray();JOBS.values().stream().sorted(Comparator.comparingLong((Job j)->j.nextAt).reversed()).limit(64).forEach(j->a.add(jobJson(j)));JsonObject o=new JsonObject();o.add("jobs",a);o.addProperty("count",a.size());return completed(c,o,"Listed scheduled jobs.");}
    private static ModelToolResult listWorkflows(ModelToolCall c){JsonArray a=new JsonArray();WORKFLOWS.values().stream().sorted(Comparator.comparingLong((Workflow w)->w.created).reversed()).limit(64).forEach(w->{JsonObject o=new JsonObject();o.addProperty("workflowId",w.id);o.addProperty("description",w.description);o.addProperty("steps",w.steps.size());a.add(o);});JsonObject o=new JsonObject();o.add("workflows",a);o.addProperty("count",a.size());return completed(c,o,"Listed compiled workflows.");}
    private static ModelToolResult cancel(ModelToolCall c){Job j=JOBS.get(string(args(c),"jobId",""));if(j==null)return failed(c,"job_not_found","No matching scheduled job exists.");j.cancelled=true;cancelFuture(j);return completed(c,jobJson(j),"Cancelled scheduled job.");}
    private static ModelToolResult delete(ModelToolCall c){String id=string(args(c),"workflowId","");Workflow w=WORKFLOWS.remove(id);JsonObject o=new JsonObject();o.addProperty("workflowId",id);o.addProperty("deleted",w!=null);return completed(c,o,w==null?"Workflow was already absent.":"Deleted compiled workflow.");}
    private static void cancelFuture(Job j){ScheduledFuture<?> f=j.future;if(f!=null&&!f.isDone())f.cancel(false);}
    private static JsonObject jobJson(Job j){JsonObject o=new JsonObject();o.addProperty("jobId",j.id);o.addProperty("workflowId",j.workflowId);o.addProperty("intervalMs",j.intervalMs);o.addProperty("maxRuns",j.maxRuns);o.addProperty("runs",j.runs.get());o.addProperty("running",j.running);o.addProperty("cancelled",j.cancelled);o.addProperty("done",j.cancelled||j.runs.get()>=j.maxRuns||(j.future!=null&&j.future.isDone()));o.addProperty("nextAtEpochMs",j.nextAt);if(j.lastStarted>0)o.addProperty("lastStartedEpochMs",j.lastStarted);if(j.lastFinished>0)o.addProperty("lastFinishedEpochMs",j.lastFinished);if(!j.lastError.isBlank())o.addProperty("lastError",j.lastError);if(j.lastResult!=null)o.add("lastResult",j.lastResult.deepCopy());return o;}
    private static Workflow resolveWorkflow(JsonObject a){return WORKFLOWS.get(string(a,"workflowId",""));}
    private static String scheduleDetail(ModelToolCall c){JsonObject a=args(c);return "workflow="+string(a,"workflowId","inline")+", intervalMs="+longVal(a,"intervalMs",0,0,Long.MAX_VALUE)+", timerId="+string(a,"timerId","");}
    private static List<ModelToolDefinition> definitions(){List<ModelToolDefinition> t=new ArrayList<>();JsonObject flow=object();props(flow).add("workflowId",str());props(flow).add("description",str());props(flow).add("steps",stepsSchema());require(flow,"steps");t.add(readwrite(WORKFLOW_DEFINE,"Compile and store a reusable workflow graph made from registered Koil tool calls. Steps may have a `when` condition over earlier step output.",flow,false));JsonObject sel=object();props(sel).add("workflowId",str());require(sel,"workflowId");t.add(mut(WORKFLOW_RUN,"Execute a compiled workflow once through the normal tool coordinator. The model does not need to micromanage each step.",sel));t.add(read(WORKFLOW_LIST,"List compiled session workflows.",object()));t.add(readwrite(WORKFLOW_DELETE,"Delete a compiled workflow definition. This does not cancel already scheduled jobs.",sel,false));JsonObject sch=object();props(sch).add("workflowId",str());props(sch).add("steps",stepsSchema());props(sch).add("delayMs",integerSchema(0,604800000));props(sch).add("timerId",str());props(sch).add("intervalMs",integerSchema(0,86400000));props(sch).add("maxRuns",integerSchema(1,100000));t.add(mut(SCHEDULE_CREATE,"Schedule a workflow once, repeatedly at intervalMs, after delayMs, or at a timer deadline. Returns immediately and runs without keeping model inference alive.",sch));JsonObject job=object();props(job).add("jobId",str());require(job,"jobId");t.add(read(SCHEDULE_STATUS,"Inspect one scheduled background job and its latest workflow result.",job));t.add(read(SCHEDULE_LIST,"List background scheduled jobs.",object()));t.add(readwrite(SCHEDULE_CANCEL,"Cancel a scheduled job without waiting for another model inference.",job,false));return List.copyOf(t);}
    private static ModelToolDefinition read(String id,String d,JsonObject s){return new ModelToolDefinition(id,d,s,List.of("automation_mode_enabled"),Set.of(),false,Duration.ofSeconds(3),false,false,Set.of("completed","failed"),ToolExecutionPolicy.readOnly(ToolExecutionPolicy.FreshnessMode.LIVE,ToolExecutionPolicy.CostClass.CHEAP));}
    private static ModelToolDefinition readwrite(String id,String d,JsonObject s,boolean conf){return new ModelToolDefinition(id,d,s,List.of("automation_mode_enabled"),Set.of("automation_state"),true,Duration.ofSeconds(3),false,conf,Set.of("completed","failed"),ToolExecutionPolicy.validateOnlyMutation(ToolExecutionPolicy.CostClass.CHEAP));}
    private static ModelToolDefinition mut(String id,String d,JsonObject s){return new ModelToolDefinition(id,d,s,List.of("automation_mode_enabled"),Set.of("scheduled_or_tool_effects"),true,Duration.ofMinutes(30),true,true,Set.of("completed","failed"),ToolExecutionPolicy.validateOnlyMutation(ToolExecutionPolicy.CostClass.MODERATE));}
    private static JsonObject stepsSchema(){JsonObject arr=new JsonObject();arr.addProperty("type","array");JsonObject item=new JsonObject();item.addProperty("type","object");JsonObject p=new JsonObject();p.add("id",str());p.add("toolId",str());JsonObject anyObj=objectLoose();p.add("arguments",anyObj);p.add("when",objectLoose());item.add("properties",p);JsonArray req=new JsonArray();req.add("toolId");item.add("required",req);arr.add("items",item);arr.addProperty("maxItems",32);return arr;}
    private static JsonObject object(){JsonObject o=new JsonObject();o.addProperty("type","object");o.addProperty("additionalProperties",false);o.add("properties",new JsonObject());return o;}private static JsonObject objectLoose(){JsonObject o=new JsonObject();o.addProperty("type","object");return o;}private static JsonObject props(JsonObject o){return o.getAsJsonObject("properties");}private static JsonObject str(){JsonObject o=new JsonObject();o.addProperty("type","string");return o;}private static JsonObject integerSchema(long min,long max){JsonObject o=new JsonObject();o.addProperty("type","integer");o.addProperty("minimum",min);o.addProperty("maximum",max);return o;}private static void require(JsonObject o,String...n){JsonArray a=new JsonArray();for(String s:n)a.add(s);o.add("required",a);}private static JsonObject args(ModelToolCall c){return c.arguments()==null?new JsonObject():c.arguments();}private static String string(JsonObject a,String k,String f){return a!=null&&a.has(k)&&!a.get(k).isJsonNull()?a.get(k).getAsString().strip():f;}private static int integer(JsonObject a,String k,int f,int min,int max){int v=a!=null&&a.has(k)?a.get(k).getAsInt():f;return Math.max(min,Math.min(max,v));}private static long longVal(JsonObject a,String k,long f,long min,long max){long v=a!=null&&a.has(k)?a.get(k).getAsLong():f;return Math.max(min,Math.min(max,v));}
    private static ModelToolResult completed(ModelToolCall c,JsonObject o,String d){return new ModelToolResult(c.id(),c.toolId(),"completed",o,"",d);}private static ModelToolResult failed(ModelToolCall c,String code,String d){return new ModelToolResult(c==null?"":c.id(),c==null?"":c.toolId(),"failed",new JsonObject(),code,d==null?"":d);}private static String msg(Throwable t){Throwable x=t;while(x.getCause()!=null)x=x.getCause();return x.getMessage()==null?x.getClass().getSimpleName():x.getMessage();}
    private record Workflow(String id,String description,JsonArray steps,long created){}
    private static final class Job{final String id,workflowId;final long intervalMs;final int maxRuns;final long nextAt;final AtomicInteger runs=new AtomicInteger();volatile boolean running,cancelled;volatile long lastStarted,lastFinished;volatile String lastError="";volatile JsonObject lastResult;volatile ScheduledFuture<?> future;Job(String id,String workflowId,long intervalMs,int maxRuns,long nextAt){this.id=id;this.workflowId=workflowId;this.intervalMs=intervalMs;this.maxRuns=maxRuns;this.nextAt=nextAt;}}
}
