package com.spirit.koil.api.model.tool;

import com.google.gson.*;
import com.spirit.koil.api.model.*;
import com.spirit.koil.api.util.text.FuzzyTextMatcher;
import com.spirit.koil.api.model.retrieval.*;

import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.CompletableFuture;

/** Structured data transforms, loss-aware context compression, and workspace-local hybrid search indexes. */
public final class DataContextIndexModelToolRegistry {
    public static final String DATA_INSPECT="data.inspect",DATA_QUERY="data.query",DATA_CONVERT="data.convert";
    public static final String CONTEXT_COMPRESS="context.compress";
    public static final String INDEX_BUILD="local_index.build",INDEX_QUERY="local_index.query",INDEX_STATUS="local_index.status";
    private static final Set<String> IDS=Set.of(DATA_INSPECT,DATA_QUERY,DATA_CONVERT,CONTEXT_COMPRESS,INDEX_BUILD,INDEX_QUERY,INDEX_STATUS);
    private static final List<ModelToolDefinition> DEFINITIONS=definitions();
    private static final Map<String,LocalIndex> INDEXES=new java.util.concurrent.ConcurrentHashMap<>();
    private DataContextIndexModelToolRegistry(){} public static String version(){return"data-context-index-tools-v1";}public static List<ModelToolDefinition>modelTools(){return DEFINITIONS;}public static boolean supports(String id){return IDS.contains(id);}
    public static CompletableFuture<ModelToolResult> execute(UUID request,ModelToolCall c,boolean preapproved){if(c==null||!supports(c.toolId()))return CompletableFuture.completedFuture(failed(c,"unknown_tool","Unknown data/context/index capability."));if(DATA_CONVERT.equals(c.toolId()))return ModelToolApproval.require(request,c,preapproved,"Write converted data",string(args(c),"outputPath","")).thenApply(ok->ok?run(c):failed(c,"approval_required","Data conversion output was not approved."));return CompletableFuture.supplyAsync(()->run(c));}
    private static ModelToolResult run(ModelToolCall c){try{return switch(c.toolId()){case DATA_INSPECT->inspect(c);case DATA_QUERY->query(c);case DATA_CONVERT->convert(c);case CONTEXT_COMPRESS->compress(c);case INDEX_BUILD->buildIndex(c);case INDEX_QUERY->queryIndex(c);case INDEX_STATUS->indexStatus(c);default->failed(c,"unknown_tool","Unknown capability.");};}catch(Exception e){return failed(c,"data_tool_failed",msg(e));}}
    private static ModelToolResult inspect(ModelToolCall c)throws Exception{Loaded d=load(args(c));JsonObject o=new JsonObject();o.addProperty("format",d.format);o.addProperty("bytes",d.raw.getBytes(StandardCharsets.UTF_8).length);o.addProperty("characters",d.raw.length());if(d.json!=null){o.addProperty("jsonType",d.json.isJsonArray()?"array":d.json.isJsonObject()?"object":"scalar");if(d.json.isJsonArray())o.addProperty("rows",d.json.getAsJsonArray().size());if(d.json.isJsonObject()){JsonArray keys=new JsonArray();d.json.getAsJsonObject().keySet().stream().limit(100).forEach(keys::add);o.add("keys",keys);}}return completed(c,o,"Inspected structured data shape without dumping the full payload.");}
    private static ModelToolResult query(ModelToolCall c)throws Exception{Loaded d=load(args(c));String q=string(args(c),"query","");JsonElement root=d.json!=null?d.json:JsonParser.parseString(toJsonText(d));JsonElement result=jsonPath(root,q);JsonObject o=new JsonObject();o.add("result",limitJson(result,integer(args(c),"maxItems",100,1,1000)));return completed(c,o,"Queried structured data with dotted path / array-index traversal.");}
    private static ModelToolResult convert(ModelToolCall c)throws Exception{JsonObject a=args(c);Loaded d=load(a);String target=string(a,"targetFormat","json").toLowerCase(Locale.ROOT);String outPath=string(a,"outputPath","");if(outPath.isBlank())return failed(c,"output_path_missing","outputPath is required for data.convert.");String rendered=render(d,target);Path out=ModelWorkspaceRegistry.resolve(string(a,"workspace","project"),outPath,true).path();Files.createDirectories(out.getParent());Files.writeString(out,rendered,StandardCharsets.UTF_8);JsonObject o=new JsonObject();o.addProperty("outputPath",out.toString());o.addProperty("targetFormat",target);o.addProperty("bytes",rendered.getBytes(StandardCharsets.UTF_8).length);return completed(c,o,"Converted structured data and wrote the approved workspace file.");}
    private static ModelToolResult compress(ModelToolCall c)throws Exception{JsonObject a=args(c);String text=string(a,"text","");if(text.isBlank()&&!string(a,"path","").isBlank())text=Files.readString(ModelWorkspaceRegistry.resolve(string(a,"workspace","project"),string(a,"path",""),false).path());int budget=integer(a,"maxCharacters",6000,500,30000);String[] lines=text.split("\\R",-1);LinkedHashMap<String,Integer> counts=new LinkedHashMap<>();for(String line:lines){String k=line.strip();if(!k.isBlank())counts.merge(k,1,Integer::sum);}StringBuilder b=new StringBuilder();b.append("[loss-aware compression] lines=").append(lines.length).append(", chars=").append(text.length()).append('\n');int head=Math.min(lines.length,Math.max(8,lines.length/6));for(int i=0;i<head&&b.length()<budget;i++)b.append(lines[i]).append('\n');if(lines.length>head*2)b.append("[... middle compressed; repeated/low-information lines omitted ...]\n");for(int i=Math.max(head,lines.length-head);i<lines.length&&b.length()<budget;i++)b.append(lines[i]).append('\n');List<Map.Entry<String,Integer>> repeated=counts.entrySet().stream().filter(e->e.getValue()>1).sorted(Map.Entry.<String,Integer>comparingByValue().reversed()).limit(20).toList();if(!repeated.isEmpty()&&b.length()<budget){b.append("[repetition counts]\n");for(var e:repeated){String row=e.getValue()+"x "+e.getKey()+"\n";if(b.length()+row.length()>budget)break;b.append(row);}}if(b.length()>budget)b.setLength(budget);JsonObject o=new JsonObject();o.addProperty("compressed",b.toString());o.addProperty("originalCharacters",text.length());o.addProperty("compressedCharacters",b.length());o.addProperty("lossy",b.length()<text.length());o.addProperty("strategy","head_tail_plus_repetition_inventory");return completed(c,o,"Compressed large context while preserving boundaries and repeated-signal counts.");}
    private static ModelToolResult buildIndex(ModelToolCall c)throws Exception{JsonObject a=args(c);String ws=string(a,"workspace","project");Path root=ModelWorkspaceRegistry.resolve(ws,string(a,"path",""),false).path();int maxFiles=integer(a,"maxFiles",2000,1,10000),maxBytes=integer(a,"maxBytesPerFile",262144,1024,1048576);List<IndexedDoc> docs=new ArrayList<>();try(var walk=Files.walk(root)){for(Path p:walk.filter(Files::isRegularFile).filter(x->!ignoredIndexPath(root,x)).limit(maxFiles).toList()){if(isProbablyBinary(p))continue;String text;try{text=Files.readString(p);if(text.length()>maxBytes)text=text.substring(0,maxBytes);}catch(Exception e){continue;}docs.add(new IndexedDoc(root.relativize(p).toString(),text,FuzzyTextMatcher.normalize(text)));}}String id="index-"+UUID.randomUUID().toString().substring(0,10);String sourceId="workspace.local_index:"+id;boolean dense=false;
        Optional<KoilRetrievalEngine> engine=KoilKnowledgeRuntime.shared();
        if(engine.isPresent()){
            ArrayList<KnowledgeEntry> entries=new ArrayList<>();int ordinal=0;
            for(IndexedDoc d:docs){Map<String,String> meta=new LinkedHashMap<>();meta.put("sourceId",sourceId);meta.put("sourceKey","file:"+(ordinal++));meta.put("indexId",id);meta.put("path",d.path);entries.add(new KnowledgeEntry(1L,KnowledgeType.WORKSPACE,"workspace",d.path+"\n"+d.text,"local_index",id,System.currentTimeMillis(),0.55D,0.85D,KnowledgeTrust.HISTORICAL_CONTEXT,meta));}
            engine.get().synchronizeSource(new KnowledgeSourceSnapshot(sourceId,Integer.toUnsignedString(docs.hashCode(),16),entries)).join();dense=engine.get().vectorHealth().entryCount()>0;
        }
        INDEXES.put(id,new LocalIndex(id,ws,root,docs,System.currentTimeMillis(),sourceId,dense));JsonObject o=new JsonObject();o.addProperty("indexId",id);o.addProperty("files",docs.size());o.addProperty("hybrid",true);o.addProperty("denseSemantic",dense);o.addProperty("semanticMode",dense?"Koil hybrid exact+dense retrieval":"fuzzy lexical fallback until embedding runtime is available");return completed(c,o,"Built workspace index and synchronized it with Koil's shared hybrid retrieval engine when available.");}
    private static ModelToolResult queryIndex(ModelToolCall c){JsonObject a=args(c);LocalIndex idx=INDEXES.get(string(a,"indexId",""));if(idx==null)return failed(c,"index_not_found","Build or select a local index first.");String q=string(a,"query","");int limit=integer(a,"limit",12,1,50);LinkedHashMap<String,JsonObject> merged=new LinkedHashMap<>();
        Optional<KoilRetrievalEngine> engine=KoilKnowledgeRuntime.shared();
        if(engine.isPresent()){try{KnowledgeFilter filter=new KnowledgeFilter(Set.of(KnowledgeType.WORKSPACE),Set.of(),Set.of(),Map.of("indexId",idx.id),0L);RetrievalResult rr=engine.get().retrieve(new KnowledgeQuery(q,filter,limit,Math.max(256,limit*96),"local-index-"+idx.id,KnowledgeTrust.HISTORICAL_CONTEXT)).join();for(RetrievalCandidate hit:rr.selected()){String path=hit.entry().metadata().getOrDefault("path","");JsonObject o=new JsonObject();o.addProperty("path",path);o.addProperty("semanticScore",hit.semanticScore());o.addProperty("exactScore",hit.exactScore());o.addProperty("fusedScore",hit.fusedScore());o.addProperty("snippet",snippet(hit.entry().text(),q,700));merged.put(path,o);}}catch(Exception ignored){}}
        record Hit(IndexedDoc d,int s){}List<Hit> hits=idx.docs.stream().map(d->{int path=FuzzyTextMatcher.score(q,d.path);int body=Math.max(FuzzyTextMatcher.score(q,d.text.length()>8000?d.text.substring(0,8000):d.text),tokenCoverage(q,d.normalized));return new Hit(d,Math.max(path,body));}).filter(h->h.s>250).sorted(Comparator.comparingInt((Hit h)->h.s).reversed()).limit(limit).toList();for(Hit h:hits)merged.computeIfAbsent(h.d.path,k->{JsonObject o=new JsonObject();o.addProperty("path",h.d.path);o.addProperty("lexicalScore",h.s);o.addProperty("snippet",snippet(h.d.text,q,700));return o;});JsonArray arr=new JsonArray();merged.values().stream().limit(limit).forEach(arr::add);JsonObject out=new JsonObject();out.add("results",arr);out.addProperty("count",arr.size());out.addProperty("denseSemantic",idx.denseSemantic);return completed(c,out,"Queried local index using Koil hybrid retrieval with lexical fallback.");}
    private static ModelToolResult indexStatus(ModelToolCall c){JsonArray a=new JsonArray();INDEXES.values().forEach(i->{JsonObject o=new JsonObject();o.addProperty("indexId",i.id);o.addProperty("workspace",i.workspace);o.addProperty("root",i.root.toString());o.addProperty("files",i.docs.size());o.addProperty("createdAtEpochMs",i.created);a.add(o);});JsonObject out=new JsonObject();out.add("indexes",a);out.addProperty("count",a.size());return completed(c,out,"Listed session local indexes.");}
    private static int tokenCoverage(String q,String text){List<String> toks=FuzzyTextMatcher.tokens(q);if(toks.isEmpty())return 0;int hit=0;for(String t:toks)if(text.contains(t))hit++;return (int)(800.0*hit/toks.size());}private static String snippet(String text,String q,int max){String n=text.toLowerCase(Locale.ROOT);int at=-1;for(String t:FuzzyTextMatcher.tokens(q)){at=n.indexOf(t);if(at>=0)break;}if(at<0)at=0;int start=Math.max(0,at-max/3),end=Math.min(text.length(),start+max);return text.substring(start,end);}
    private static Loaded load(JsonObject a)throws Exception{String text=string(a,"text","");String path=string(a,"path","");if(text.isBlank()&&!path.isBlank())text=Files.readString(ModelWorkspaceRegistry.resolve(string(a,"workspace","project"),path,false).path());if(text.isBlank())throw new IllegalArgumentException("text or path is required.");String fmt=string(a,"format","auto").toLowerCase(Locale.ROOT);if("auto".equals(fmt))fmt=detectFormat(path,text);JsonElement json=switch(fmt){case"json"->JsonParser.parseString(text);case"csv"->csvToJson(text);case"xml"->xmlToJson(text);case"yaml","yml","toml"->kvToJson(text,fmt);default->null;};return new Loaded(fmt,text,json);}
    private static String detectFormat(String path,String text){String l=path.toLowerCase(Locale.ROOT);for(String f:List.of("json","csv","xml","yaml","yml","toml"))if(l.endsWith("."+f))return f;String s=text.stripLeading();if(s.startsWith("{")||s.startsWith("["))return"json";if(s.startsWith("<"))return"xml";return"csv";}
    private static JsonElement csvToJson(String t){String[] lines=t.split("\\R");JsonArray out=new JsonArray();if(lines.length==0)return out;List<String> head=parseCsv(lines[0]);for(int i=1;i<lines.length;i++){List<String> row=parseCsv(lines[i]);JsonObject o=new JsonObject();for(int j=0;j<head.size();j++)o.addProperty(head.get(j),j<row.size()?row.get(j):"");out.add(o);}return out;}private static List<String>parseCsv(String s){ArrayList<String>r=new ArrayList<>();StringBuilder b=new StringBuilder();boolean q=false;for(int i=0;i<s.length();i++){char c=s.charAt(i);if(c=='"'){if(q&&i+1<s.length()&&s.charAt(i+1)=='"'){b.append('"');i++;}else q=!q;}else if(c==','&&!q){r.add(b.toString());b.setLength(0);}else b.append(c);}r.add(b.toString());return r;}
    private static JsonElement xmlToJson(String t)throws Exception{var b=DocumentBuilderFactory.newInstance().newDocumentBuilder();Document d=b.parse(new ByteArrayInputStream(t.getBytes(StandardCharsets.UTF_8)));return xmlNode(d.getDocumentElement());}private static JsonElement xmlNode(Element e){JsonObject o=new JsonObject();if(e.hasAttributes()){JsonObject attrs=new JsonObject();for(int i=0;i<e.getAttributes().getLength();i++){Node n=e.getAttributes().item(i);attrs.addProperty(n.getNodeName(),n.getNodeValue());}o.add("@attributes",attrs);}NodeList list=e.getChildNodes();StringBuilder text=new StringBuilder();for(int i=0;i<list.getLength();i++){Node n=list.item(i);if(n instanceof Element child){JsonElement cj=xmlNode(child);if(o.has(child.getTagName())){JsonArray a=o.get(child.getTagName()).isJsonArray()?o.getAsJsonArray(child.getTagName()):new JsonArray();if(!o.get(child.getTagName()).isJsonArray()){a.add(o.get(child.getTagName()));o.add(child.getTagName(),a);}a.add(cj);}else o.add(child.getTagName(),cj);}else if(n.getNodeType()==Node.TEXT_NODE)text.append(n.getTextContent().strip());}if(!text.isEmpty())o.addProperty("#text",text.toString());JsonObject wrap=new JsonObject();wrap.add(e.getTagName(),o);return wrap;}
    private static JsonElement kvToJson(String t,String f){JsonObject o=new JsonObject();for(String line:t.split("\\R")){String s=line.strip();if(s.isBlank()||s.startsWith("#")||s.startsWith("["))continue;int p=s.indexOf(f.startsWith("toml")?'=':':');if(p<=0)continue;String k=s.substring(0,p).strip(),v=s.substring(p+1).strip().replaceAll("^[\"']|[\"']$","");o.addProperty(k,v);}return o;}
    private static JsonElement jsonPath(JsonElement root,String q){if(q==null||q.isBlank()||"$".equals(q))return root;JsonElement cur=root;for(String part:q.replace("$.","").split("\\.")){if(part.isBlank())continue;int b=part.indexOf('[');String key=b>=0?part.substring(0,b):part;if(!key.isBlank()){if(!cur.isJsonObject())return JsonNull.INSTANCE;cur=cur.getAsJsonObject().get(key);}if(b>=0){int e=part.indexOf(']',b);int idx=Integer.parseInt(part.substring(b+1,e));if(cur==null||!cur.isJsonArray()||idx>=cur.getAsJsonArray().size())return JsonNull.INSTANCE;cur=cur.getAsJsonArray().get(idx);}if(cur==null)return JsonNull.INSTANCE;}return cur;}
    private static JsonElement limitJson(JsonElement e,int max){if(e==null)return JsonNull.INSTANCE;if(e.isJsonArray()&&e.getAsJsonArray().size()>max){JsonArray a=new JsonArray();for(int i=0;i<max;i++)a.add(e.getAsJsonArray().get(i));return a;}return e.deepCopy();}
    private static String toJsonText(Loaded d){return d.json==null?new JsonPrimitive(d.raw).toString():d.json.toString();}private static String render(Loaded d,String target){JsonElement j=d.json!=null?d.json:JsonParser.parseString(toJsonText(d));if("json".equals(target))return new GsonBuilder().setPrettyPrinting().create().toJson(j);if("csv".equals(target)&&j.isJsonArray()){JsonArray a=j.getAsJsonArray();if(a.isEmpty())return"";Set<String>keys=new LinkedHashSet<>();a.forEach(x->{if(x.isJsonObject())keys.addAll(x.getAsJsonObject().keySet());});StringBuilder b=new StringBuilder(String.join(",",keys)).append('\n');for(JsonElement row:a){int i=0;for(String k:keys){if(i++>0)b.append(',');String v=row.isJsonObject()&&row.getAsJsonObject().has(k)?row.getAsJsonObject().get(k).getAsString():"";b.append('"').append(v.replace("\"","\"\"")).append('"');}b.append('\n');}return b.toString();}throw new IllegalArgumentException("targetFormat currently supports json or csv.");}
    private static boolean isProbablyBinary(Path p){String n=p.getFileName().toString().toLowerCase(Locale.ROOT);return n.matches(".*\\.(png|jpg|jpeg|gif|webp|zip|jar|class|so|dll|dylib|pdf|mp3|mp4|ogg|wav)$");}
    private static boolean ignoredIndexPath(Path root,Path p){Path rel=root.relativize(p);for(Path part:rel){String n=part.toString().toLowerCase(Locale.ROOT);if(Set.of(".git",".gradle","build","target","node_modules",".venv","dist","out").contains(n))return true;}return false;}
    private static List<ModelToolDefinition>definitions(){List<ModelToolDefinition>t=new ArrayList<>();JsonObject data=object();for(String k:List.of("workspace","path","text","format","query"))props(data).add(k,str());props(data).add("maxItems",integerSchema(1,1000));t.add(read(DATA_INSPECT,"Inspect JSON/CSV/XML/YAML/TOML shape and metadata without dumping the entire dataset.",data,ToolExecutionPolicy.FreshnessMode.WORKSPACE));t.add(read(DATA_QUERY,"Query JSON/CSV/XML/YAML/TOML through a compact dotted path and bounded results.",data,ToolExecutionPolicy.FreshnessMode.WORKSPACE));JsonObject cv=data.deepCopy();props(cv).add("targetFormat",enm("json","csv"));props(cv).add("outputPath",str());t.add(new ModelToolDefinition(DATA_CONVERT,"Convert supported structured data to JSON or CSV and write the result inside a workspace.",cv,List.of("automation_mode_enabled"),Set.of("workspace_files"),true,Duration.ofSeconds(30),true,true,Set.of("completed","failed"),ToolExecutionPolicy.validateOnlyMutation(ToolExecutionPolicy.CostClass.MODERATE)));JsonObject comp=object();for(String k:List.of("workspace","path","text"))props(comp).add(k,str());props(comp).add("maxCharacters",integerSchema(500,30000));t.add(read(CONTEXT_COMPRESS,"Compress large logs/tool output into bounded evidence using head/tail retention plus repetition inventory, reducing context-window pressure without pretending it is lossless.",comp,ToolExecutionPolicy.FreshnessMode.LIVE));JsonObject bi=object();props(bi).add("workspace",str());props(bi).add("path",str());props(bi).add("maxFiles",integerSchema(1,10000));props(bi).add("maxBytesPerFile",integerSchema(1024,1048576));t.add(read(INDEX_BUILD,"Build a session-local full-text and fuzzy-semantic index across arbitrary workspace files, logs, docs, configs, and source.",bi,ToolExecutionPolicy.FreshnessMode.WORKSPACE));JsonObject qi=object();props(qi).add("indexId",str());props(qi).add("query",str());props(qi).add("limit",integerSchema(1,50));t.add(read(INDEX_QUERY,"Search a previously built local workspace index by path/content with hybrid literal and fuzzy-semantic scoring.",qi,ToolExecutionPolicy.FreshnessMode.WORKSPACE));t.add(read(INDEX_STATUS,"List current local workspace indexes and their coverage.",object(),ToolExecutionPolicy.FreshnessMode.LIVE));return List.copyOf(t);}private static ModelToolDefinition read(String id,String d,JsonObject s,ToolExecutionPolicy.FreshnessMode f){return new ModelToolDefinition(id,d,s,List.of("automation_mode_enabled"),Set.of(),false,Duration.ofSeconds(60),true,false,Set.of("completed","failed"),ToolExecutionPolicy.readOnly(f,ToolExecutionPolicy.CostClass.MODERATE));}
    private static JsonObject object(){JsonObject o=new JsonObject();o.addProperty("type","object");o.addProperty("additionalProperties",false);o.add("properties",new JsonObject());return o;}private static JsonObject props(JsonObject o){return o.getAsJsonObject("properties");}private static JsonObject str(){JsonObject o=new JsonObject();o.addProperty("type","string");return o;}private static JsonObject integerSchema(int min,int max){JsonObject o=new JsonObject();o.addProperty("type","integer");o.addProperty("minimum",min);o.addProperty("maximum",max);return o;}private static JsonObject enm(String...v){JsonObject o=str();JsonArray a=new JsonArray();for(String s:v)a.add(s);o.add("enum",a);return o;}private static JsonObject args(ModelToolCall c){return c.arguments()==null?new JsonObject():c.arguments();}private static String string(JsonObject a,String k,String f){return a!=null&&a.has(k)&&!a.get(k).isJsonNull()?a.get(k).getAsString().strip():f;}private static int integer(JsonObject a,String k,int f,int min,int max){int v=a!=null&&a.has(k)?a.get(k).getAsInt():f;return Math.max(min,Math.min(max,v));}private static ModelToolResult completed(ModelToolCall c,JsonObject o,String d){return new ModelToolResult(c.id(),c.toolId(),"completed",o,"",d);}private static ModelToolResult failed(ModelToolCall c,String code,String d){return new ModelToolResult(c==null?"":c.id(),c==null?"":c.toolId(),"failed",new JsonObject(),code,d==null?"":d);}private static String msg(Throwable t){return t.getMessage()==null?t.getClass().getSimpleName():t.getMessage();}
    private record Loaded(String format,String raw,JsonElement json){}private record IndexedDoc(String path,String text,String normalized){}private record LocalIndex(String id,String workspace,Path root,List<IndexedDoc>docs,long created,String sourceId,boolean denseSemantic){}
}
