package com.spirit.koil.api.model.tool;

import com.google.gson.*;
import com.spirit.koil.api.model.*;

import java.lang.management.ManagementFactory;
import java.net.*;
import java.net.http.*;
import java.nio.file.FileStore;
import java.nio.file.FileSystems;
import java.nio.file.Path;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.CompletableFuture;

/** Local machine resource visibility and bounded network diagnostics. */
public final class SystemNetworkModelToolRegistry {
    public static final String DNS="network.dns",TCP="network.tcp",HTTP="network.http",LATENCY="network.latency",RESOURCES="system.resources",PROCESSES="system.processes";
    private static final Set<String> IDS=Set.of(DNS,TCP,HTTP,LATENCY,RESOURCES,PROCESSES);private static final List<ModelToolDefinition> DEFINITIONS=definitions();
    private SystemNetworkModelToolRegistry(){}public static String version(){return"system-network-tools-v1";}public static List<ModelToolDefinition>modelTools(){return DEFINITIONS;}public static boolean supports(String id){return IDS.contains(id);}
    public static CompletableFuture<ModelToolResult> execute(ModelToolCall c){return CompletableFuture.supplyAsync(()->run(c));}
    private static ModelToolResult run(ModelToolCall c){if(c==null||!supports(c.toolId()))return failed(c,"unknown_tool","Unknown system/network capability.");try{return switch(c.toolId()){case DNS->dns(c);case TCP->tcp(c);case HTTP->http(c);case LATENCY->latency(c);case RESOURCES->resources(c);case PROCESSES->processes(c);default->failed(c,"unknown_tool","Unknown system/network capability.");};}catch(Exception e){return failed(c,"diagnostic_failed",msg(e));}}
    private static ModelToolResult dns(ModelToolCall c)throws Exception{String host=string(args(c),"host","");if(host.isBlank())return failed(c,"host_missing","host is required.");JsonArray a=new JsonArray();for(InetAddress x:InetAddress.getAllByName(host)){JsonObject o=new JsonObject();o.addProperty("address",x.getHostAddress());o.addProperty("canonicalHost",x.getCanonicalHostName());a.add(o);}JsonObject out=new JsonObject();out.addProperty("host",host);out.add("addresses",a);return completed(c,out,"Resolved host with the JVM DNS resolver.");}
    private static ModelToolResult tcp(ModelToolCall c)throws Exception{JsonObject a=args(c);String host=string(a,"host","");int port=integer(a,"port",0,1,65535),timeout=integer(a,"timeoutMs",2000,100,10000);long start=System.nanoTime();boolean ok;String error="";try(Socket s=new Socket()){s.connect(new InetSocketAddress(host,port),timeout);ok=true;}catch(Exception e){ok=false;error=msg(e);}JsonObject out=new JsonObject();out.addProperty("host",host);out.addProperty("port",port);out.addProperty("reachable",ok);out.addProperty("latencyMs",(System.nanoTime()-start)/1_000_000.0);if(!error.isBlank())out.addProperty("error",error);return completed(c,out,"Performed bounded TCP reachability check.");}
    private static ModelToolResult http(ModelToolCall c)throws Exception{JsonObject a=args(c);URI uri=URI.create(string(a,"url",""));String scheme=uri.getScheme()==null?"":uri.getScheme().toLowerCase(Locale.ROOT);if(!Set.of("http","https").contains(scheme))return failed(c,"unsupported_scheme","Only http/https diagnostics are supported.");int timeout=integer(a,"timeoutMs",5000,100,15000);HttpClient client=HttpClient.newBuilder().connectTimeout(Duration.ofMillis(timeout)).followRedirects(HttpClient.Redirect.NORMAL).build();HttpRequest req=HttpRequest.newBuilder(uri).timeout(Duration.ofMillis(timeout)).method(string(a,"method","HEAD").toUpperCase(Locale.ROOT),HttpRequest.BodyPublishers.noBody()).build();long st=System.nanoTime();HttpResponse<Void> r=client.send(req,HttpResponse.BodyHandlers.discarding());JsonObject out=new JsonObject();out.addProperty("status",r.statusCode());out.addProperty("finalUrl",r.uri().toString());out.addProperty("latencyMs",(System.nanoTime()-st)/1_000_000.0);JsonObject h=new JsonObject();r.headers().map().forEach((k,v)->h.addProperty(k,String.join(", ",v)));out.add("headers",h);return completed(c,out,"Performed bounded HTTP diagnostic request without browser automation.");}
    private static ModelToolResult latency(ModelToolCall c)throws Exception{JsonObject a=args(c);String host=string(a,"host","");int port=integer(a,"port",443,1,65535),count=integer(a,"count",3,1,10);JsonArray samples=new JsonArray();double total=0;int success=0;for(int i=0;i<count;i++){long st=System.nanoTime();try(Socket s=new Socket()){s.connect(new InetSocketAddress(host,port),integer(a,"timeoutMs",2000,100,10000));double ms=(System.nanoTime()-st)/1_000_000.0;samples.add(ms);total+=ms;success++;}catch(Exception e){samples.add(JsonNull.INSTANCE);}}JsonObject out=new JsonObject();out.add("samplesMs",samples);out.addProperty("successful",success);if(success>0)out.addProperty("averageMs",total/success);return completed(c,out,"Measured TCP-connect latency samples.");}
    private static ModelToolResult resources(ModelToolCall c)throws Exception{JsonObject o=new JsonObject();Runtime r=Runtime.getRuntime();o.addProperty("processors",r.availableProcessors());o.addProperty("jvmMaxMemoryBytes",r.maxMemory());o.addProperty("jvmTotalMemoryBytes",r.totalMemory());o.addProperty("jvmFreeMemoryBytes",r.freeMemory());o.addProperty("systemLoadAverage",ManagementFactory.getOperatingSystemMXBean().getSystemLoadAverage());try{com.sun.management.OperatingSystemMXBean os=(com.sun.management.OperatingSystemMXBean)ManagementFactory.getOperatingSystemMXBean();o.addProperty("physicalMemoryTotalBytes",os.getTotalMemorySize());o.addProperty("physicalMemoryFreeBytes",os.getFreeMemorySize());o.addProperty("cpuLoad",os.getCpuLoad());}catch(Throwable ignored){}JsonArray stores=new JsonArray();for(FileStore fs:FileSystems.getDefault().getFileStores()){try{JsonObject d=new JsonObject();d.addProperty("name",fs.name());d.addProperty("type",fs.type());d.addProperty("totalBytes",fs.getTotalSpace());d.addProperty("usableBytes",fs.getUsableSpace());stores.add(d);}catch(Exception ignored){}}o.add("storage",stores);JsonArray gpu=new JsonArray();for(List<String> cmd:List.of(List.of("nvidia-smi","--query-gpu=name,memory.total,memory.used,utilization.gpu","--format=csv,noheader,nounits"),List.of("rocm-smi","--showproductname","--showmeminfo","vram"),List.of("lspci"))){try{var pr=WorkspaceProcessService.run(Path.of("."),cmd,System.getenv(),4);if(pr.exitCode()!=0||pr.stdout().isBlank())continue;String text=pr.stdout();if("lspci".equals(cmd.get(0)))text=Arrays.stream(text.split("\\R")).filter(line->{String x=line.toLowerCase(Locale.ROOT);return x.contains("vga")||x.contains("3d controller")||x.contains("display controller");}).reduce("",(a,b)->a+(a.isBlank()?"":"\n")+b);if(text.isBlank())continue;JsonObject g=new JsonObject();g.addProperty("probe",cmd.get(0));g.addProperty("output",truncate(text,4000));gpu.add(g);break;}catch(Exception ignored){}}o.add("gpu",gpu);return completed(c,o,"Read local CPU, memory, GPU probe, load, and storage resources.");}
    private static ModelToolResult processes(ModelToolCall c){int limit=integer(args(c),"limit",50,1,200);JsonArray a=new JsonArray();ProcessHandle.allProcesses().limit(limit).forEach(p->{JsonObject o=new JsonObject();o.addProperty("pid",p.pid());ProcessHandle.Info i=p.info();i.command().ifPresent(v->o.addProperty("command",v));i.commandLine().ifPresent(v->o.addProperty("commandLine",sanitizeCommandLine(truncate(v,500))));i.totalCpuDuration().ifPresent(v->o.addProperty("cpuMillis",v.toMillis()));a.add(o);});JsonObject out=new JsonObject();out.add("processes",a);out.addProperty("count",a.size());return completed(c,out,"Listed bounded local process metadata.");}
    private static List<ModelToolDefinition>definitions(){List<ModelToolDefinition>t=new ArrayList<>();JsonObject host=object();props(host).add("host",str());require(host,"host");t.add(read(DNS,"Resolve DNS names locally and return addresses/canonical names.",host));JsonObject tcp=host.deepCopy();props(tcp).add("port",integerSchema(1,65535));props(tcp).add("timeoutMs",integerSchema(100,10000));require(tcp,"host","port");t.add(read(TCP,"Test TCP reachability to host:port with bounded timeout.",tcp));JsonObject http=object();props(http).add("url",str());props(http).add("method",enm("HEAD","GET"));props(http).add("timeoutMs",integerSchema(100,15000));require(http,"url");t.add(read(HTTP,"Perform lightweight HTTP diagnostics such as status, redirects, headers, and request latency. Not a browser/search tool.",http));JsonObject lat=tcp.deepCopy();props(lat).add("count",integerSchema(1,10));t.add(read(LATENCY,"Measure several bounded TCP-connect latency samples.",lat));t.add(read(RESOURCES,"Inspect CPU count/load, RAM, JVM memory, and storage so the model can make hardware-aware execution choices.",object()));JsonObject proc=object();props(proc).add("limit",integerSchema(1,200));t.add(read(PROCESSES,"List bounded local OS process metadata for diagnostics; does not terminate processes.",proc));return List.copyOf(t);}private static ModelToolDefinition read(String id,String d,JsonObject s){return new ModelToolDefinition(id,d,s,List.of("automation_mode_enabled"),Set.of(),false,Duration.ofSeconds(20),true,false,Set.of("completed","failed"),ToolExecutionPolicy.readOnly(ToolExecutionPolicy.FreshnessMode.LIVE,ToolExecutionPolicy.CostClass.CHEAP));}
    private static JsonObject object(){JsonObject o=new JsonObject();o.addProperty("type","object");o.addProperty("additionalProperties",false);o.add("properties",new JsonObject());return o;}private static JsonObject props(JsonObject o){return o.getAsJsonObject("properties");}private static JsonObject str(){JsonObject o=new JsonObject();o.addProperty("type","string");return o;}private static JsonObject integerSchema(int min,int max){JsonObject o=new JsonObject();o.addProperty("type","integer");o.addProperty("minimum",min);o.addProperty("maximum",max);return o;}private static JsonObject enm(String...v){JsonObject o=str();JsonArray a=new JsonArray();for(String s:v)a.add(s);o.add("enum",a);return o;}private static void require(JsonObject o,String...n){JsonArray a=new JsonArray();for(String s:n)a.add(s);o.add("required",a);}private static JsonObject args(ModelToolCall c){return c.arguments()==null?new JsonObject():c.arguments();}private static String string(JsonObject a,String k,String f){return a!=null&&a.has(k)&&!a.get(k).isJsonNull()?a.get(k).getAsString().strip():f;}private static int integer(JsonObject a,String k,int f,int min,int max){int v=a!=null&&a.has(k)?a.get(k).getAsInt():f;return Math.max(min,Math.min(max,v));}private static String truncate(String s,int n){return s.length()<=n?s:s.substring(0,n)+"…";}private static String sanitizeCommandLine(String s){if(s==null||s.isBlank())return "";String[] parts=s.split("\\s+");StringBuilder out=new StringBuilder();boolean redactNext=false;for(String part:parts){String lower=part.toLowerCase(Locale.ROOT);if(redactNext){part="***";redactNext=false;}else if(lower.matches(".*(token|secret|password|passwd|apikey|api_key|credential).*")){int eq=part.indexOf('=');if(eq>=0)part=part.substring(0,eq+1)+"***";else redactNext=true;}if(out.length()>0)out.append(' ');out.append(part);}return out.toString();}private static ModelToolResult completed(ModelToolCall c,JsonObject o,String d){return new ModelToolResult(c.id(),c.toolId(),"completed",o,"",d);}private static ModelToolResult failed(ModelToolCall c,String code,String d){return new ModelToolResult(c==null?"":c.id(),c==null?"":c.toolId(),"failed",new JsonObject(),code,d==null?"":d);}private static String msg(Throwable t){return t.getMessage()==null?t.getClass().getSimpleName():t.getMessage();}
}
