package com.spirit.koil.api.model.tool;

import com.google.gson.*;
import com.spirit.koil.api.model.*;

import java.nio.file.Path;
import java.sql.*;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.CompletableFuture;

/** SQLite/JDBC database inspection and bounded querying. */
public final class WorkspaceDatabaseModelToolRegistry {
    public static final String INSPECT="database.inspect", QUERY="database.query", EXPLAIN="database.explain", EXECUTE="database.execute";
    private static final List<ModelToolDefinition> DEFINITIONS=definitions();
    private WorkspaceDatabaseModelToolRegistry(){}
    public static String version(){return "workspace-database-tools-v1";} public static List<ModelToolDefinition> modelTools(){return DEFINITIONS;} public static boolean supports(String id){return Set.of(INSPECT,QUERY,EXPLAIN,EXECUTE).contains(id);}
    public static CompletableFuture<ModelToolResult> execute(UUID request,ModelToolCall call,boolean preapproved){if(call==null||!supports(call.toolId()))return CompletableFuture.completedFuture(failed(call,"unknown_database_tool","Unknown database capability."));if(EXECUTE.equals(call.toolId()))return ModelToolApproval.require(request,call,preapproved,"Database mutation approval",string(call.arguments(),"sql","")).thenApply(ok->ok?run(call):failed(call,"approval_required","Database mutation was not approved."));return CompletableFuture.supplyAsync(()->run(call));}
    private static ModelToolResult run(ModelToolCall c){JsonObject a=args(c);try{String url=jdbcUrl(a);try(Connection db=DriverManager.getConnection(url)){return switch(c.toolId()){case INSPECT->inspect(c,db,url);case QUERY->query(c,db,string(a,"sql",""),integer(a,"maxRows",100,1,1000));case EXPLAIN->query(c,db,"EXPLAIN QUERY PLAN "+string(a,"sql",""),integer(a,"maxRows",100,1,1000));case EXECUTE->executeMutation(c,db,string(a,"sql",""));default->failed(c,"unknown_database_tool","Unknown database capability.");};}}catch(SQLException e){if(string(a,"jdbcUrl","").isBlank()&&!string(a,"path","").isBlank()&&e.getMessage()!=null&&e.getMessage().toLowerCase(Locale.ROOT).contains("no suitable driver")){try{return sqliteCli(c,a);}catch(Exception cli){return failed(c,"database_driver_unavailable","SQLite JDBC driver is unavailable and sqlite3 CLI fallback failed: "+msg(cli));}}return failed(c,"database_error",e.getMessage()==null?e.getClass().getSimpleName():e.getMessage());}catch(Exception e){return failed(c,"database_error",msg(e));}}

    private static ModelToolResult sqliteCli(ModelToolCall c,JsonObject a)throws Exception{
        Path file=ModelWorkspaceRegistry.resolve(string(a,"workspace","project"),string(a,"path",""),true).path();
        String sql=string(a,"sql","");
        ArrayList<String> cmd=new ArrayList<>();cmd.add("sqlite3");cmd.add("-json");cmd.add(file.toString());
        if(INSPECT.equals(c.toolId())) sql="SELECT name,type,sql FROM sqlite_master WHERE type IN ('table','view') ORDER BY name;";
        else if(EXPLAIN.equals(c.toolId())) sql="EXPLAIN QUERY PLAN "+sql;
        cmd.add(sql);
        WorkspaceProcessService.RunResult r=WorkspaceProcessService.run(file.getParent()==null?Path.of("."):file.getParent(),cmd,System.getenv(),30);
        JsonObject out=new JsonObject();out.addProperty("backend","sqlite3-cli");out.addProperty("database",file.toString());out.addProperty("stdout",r.stdout());out.addProperty("stderr",r.stderr());out.addProperty("exitCode",r.exitCode());
        return r.exitCode()==0?completed(c,out,"Executed SQLite operation through sqlite3 CLI fallback."):new ModelToolResult(c.id(),c.toolId(),"failed",out,"sqlite_cli_failed","sqlite3 exited with code "+r.exitCode()+".");
    }

    private static String jdbcUrl(JsonObject a)throws Exception{String u=string(a,"jdbcUrl","");if(!u.isBlank())return u;String ws=string(a,"workspace","project");String p=string(a,"path","");if(p.isBlank())throw new IllegalArgumentException("path or jdbcUrl is required.");Path file=ModelWorkspaceRegistry.resolve(ws,p,true).path();return"jdbc:sqlite:"+file;}
    private static ModelToolResult inspect(ModelToolCall c,Connection db,String url)throws SQLException{JsonObject o=new JsonObject();o.addProperty("jdbcUrl",mask(url));DatabaseMetaData m=db.getMetaData();o.addProperty("databaseProduct",m.getDatabaseProductName());o.addProperty("databaseVersion",m.getDatabaseProductVersion());JsonArray tables=new JsonArray();try(ResultSet rs=m.getTables(null,null,"%",new String[]{"TABLE","VIEW"})){int n=0;while(rs.next()&&n++<200){JsonObject t=new JsonObject();String name=rs.getString("TABLE_NAME");t.addProperty("name",name);t.addProperty("type",rs.getString("TABLE_TYPE"));JsonArray cols=new JsonArray();try(ResultSet cr=m.getColumns(null,null,name,"%")){while(cr.next()){JsonObject col=new JsonObject();col.addProperty("name",cr.getString("COLUMN_NAME"));col.addProperty("type",cr.getString("TYPE_NAME"));col.addProperty("nullable",cr.getInt("NULLABLE")!=DatabaseMetaData.columnNoNulls);cols.add(col);}}t.add("columns",cols);tables.add(t);}}o.add("tables",tables);return completed(c,o,"Inspected database schema through JDBC metadata.");}
    private static ModelToolResult query(ModelToolCall c,Connection db,String sql,int maxRows)throws SQLException{if(sql.isBlank())return failed(c,"sql_missing","sql is required.");String lead=sql.stripLeading().toLowerCase(Locale.ROOT);if(!(lead.startsWith("select")||lead.startsWith("with")||lead.startsWith("pragma")||lead.startsWith("explain")))return failed(c,"query_not_read_only","database.query/explain only accept read-only SQL; use database.execute for mutations.");try(Statement st=db.createStatement()){st.setMaxRows(maxRows);try(ResultSet rs=st.executeQuery(sql)){JsonObject o=new JsonObject();JsonArray rows=new JsonArray();ResultSetMetaData md=rs.getMetaData();int cc=md.getColumnCount(),n=0;while(rs.next()&&n++<maxRows){JsonObject row=new JsonObject();for(int i=1;i<=cc;i++){Object v=rs.getObject(i);if(v==null)row.add(md.getColumnLabel(i),JsonNull.INSTANCE);else if(v instanceof Number num)row.addProperty(md.getColumnLabel(i),num);else if(v instanceof Boolean b)row.addProperty(md.getColumnLabel(i),b);else row.addProperty(md.getColumnLabel(i),String.valueOf(v));}rows.add(row);}o.add("rows",rows);o.addProperty("rowCount",rows.size());o.addProperty("maxRows",maxRows);return completed(c,o,"Executed bounded read-only database query.");}}
    }
    private static ModelToolResult executeMutation(ModelToolCall c,Connection db,String sql)throws SQLException{if(sql.isBlank())return failed(c,"sql_missing","sql is required.");try(Statement st=db.createStatement()){int affected=st.executeUpdate(sql);JsonObject o=new JsonObject();o.addProperty("affectedRows",affected);return completed(c,o,"Executed approved database mutation.");}}
    private static String mask(String url){int at=url.indexOf('@');if(at>0){int scheme=url.indexOf("://");if(scheme>=0)return url.substring(0,scheme+3)+"***@"+url.substring(at+1);}return url;}
    private static List<ModelToolDefinition> definitions(){JsonObject base=object();props(base).add("workspace",str());props(base).add("path",str());props(base).add("jdbcUrl",str());JsonObject q=base.deepCopy();props(q).add("sql",str());props(q).add("maxRows",integerSchema(1,1000));JsonObject x=base.deepCopy();props(x).add("sql",str());return List.of(read(INSPECT,"Inspect SQLite or any available JDBC database schema, tables, columns, and database metadata.",base,ToolExecutionPolicy.FreshnessMode.WORKSPACE),read(QUERY,"Run bounded read-only SQL against SQLite/JDBC. SELECT/WITH/PRAGMA only; never mutates data.",q,ToolExecutionPolicy.FreshnessMode.LIVE),read(EXPLAIN,"Explain a query plan without executing a mutation. For SQLite this uses EXPLAIN QUERY PLAN.",q,ToolExecutionPolicy.FreshnessMode.LIVE),new ModelToolDefinition(EXECUTE,"Execute an approved SQL mutation against SQLite/JDBC. Use only when the user actually wants data/schema changed.",x,List.of("automation_mode_enabled"),Set.of("database"),true,Duration.ofSeconds(30),true,true,Set.of("completed","failed"),ToolExecutionPolicy.validateOnlyMutation(ToolExecutionPolicy.CostClass.MODERATE)));}
    private static ModelToolDefinition read(String id,String d,JsonObject s,ToolExecutionPolicy.FreshnessMode f){return new ModelToolDefinition(id,d,s,List.of("automation_mode_enabled"),Set.of(),false,Duration.ofSeconds(30),true,false,Set.of("completed","failed"),ToolExecutionPolicy.readOnly(f,ToolExecutionPolicy.CostClass.MODERATE));}
    private static JsonObject object(){JsonObject o=new JsonObject();o.addProperty("type","object");o.addProperty("additionalProperties",false);o.add("properties",new JsonObject());return o;}private static JsonObject props(JsonObject o){return o.getAsJsonObject("properties");}private static JsonObject str(){JsonObject o=new JsonObject();o.addProperty("type","string");return o;}private static JsonObject integerSchema(int min,int max){JsonObject o=new JsonObject();o.addProperty("type","integer");o.addProperty("minimum",min);o.addProperty("maximum",max);return o;}private static JsonObject args(ModelToolCall c){return c.arguments()==null?new JsonObject():c.arguments();}private static String string(JsonObject a,String k,String f){return a!=null&&a.has(k)&&!a.get(k).isJsonNull()?a.get(k).getAsString().strip():f;}private static int integer(JsonObject a,String k,int f,int min,int max){int v=a!=null&&a.has(k)?a.get(k).getAsInt():f;return Math.max(min,Math.min(max,v));}private static ModelToolResult completed(ModelToolCall c,JsonObject o,String d){return new ModelToolResult(c.id(),c.toolId(),"completed",o,"",d);}private static ModelToolResult failed(ModelToolCall c,String code,String d){return new ModelToolResult(c==null?"":c.id(),c==null?"":c.toolId(),"failed",new JsonObject(),code,d==null?"":d);}private static String msg(Throwable t){return t.getMessage()==null?t.getClass().getSimpleName():t.getMessage();}
}
