package com.spirit.koil.api.model.tool;

import com.google.gson.*;
import com.spirit.koil.api.model.*;

import java.io.*;
import java.nio.file.*;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.CompletableFuture;
import java.util.zip.*;

/** Git operations plus ZIP/TAR archive inspection and mutation. */
public final class WorkspaceGitArchiveModelToolRegistry {
    public static final String GIT_STATUS="git.status",GIT_DIFF="git.diff",GIT_LOG="git.log",GIT_BRANCHES="git.branches",GIT_STAGE="git.stage",GIT_COMMIT="git.commit",GIT_INSPECT="git.inspect";
    public static final String ARC_INSPECT="archive.inspect",ARC_CREATE="archive.create",ARC_EXTRACT="archive.extract",ARC_COMPARE="archive.compare",ARC_PATCH="archive.patch";
    private static final Set<String> IDS=Set.of(GIT_STATUS,GIT_DIFF,GIT_LOG,GIT_BRANCHES,GIT_STAGE,GIT_COMMIT,GIT_INSPECT,ARC_INSPECT,ARC_CREATE,ARC_EXTRACT,ARC_COMPARE,ARC_PATCH);
    private static final List<ModelToolDefinition> DEFINITIONS=definitions();
    private WorkspaceGitArchiveModelToolRegistry(){}
    public static String version(){return "workspace-git-archive-tools-v1";}public static List<ModelToolDefinition> modelTools(){return DEFINITIONS;}public static boolean supports(String id){return IDS.contains(id);}
    public static CompletableFuture<ModelToolResult> execute(UUID request,ModelToolCall c,boolean preapproved){if(c==null||!supports(c.toolId()))return CompletableFuture.completedFuture(failed(c,"unknown_tool","Unknown git/archive capability."));boolean mut=Set.of(GIT_STAGE,GIT_COMMIT,ARC_CREATE,ARC_EXTRACT,ARC_PATCH).contains(c.toolId());if(!mut)return CompletableFuture.supplyAsync(()->run(c));return ModelToolApproval.require(request,c,preapproved,"Workspace mutation approval",c.toolId()).thenApply(ok->ok?run(c):failed(c,"approval_required","Workspace mutation was not approved."));}
    private static ModelToolResult run(ModelToolCall c){try{return c.toolId().startsWith("git.")?git(c):archive(c);}catch(Exception e){return failed(c,"operation_failed",msg(e));}}
    private static ModelToolResult git(ModelToolCall c)throws Exception{JsonObject a=args(c);Path cwd=ModelWorkspaceRegistry.resolve(string(a,"workspace","project"),string(a,"cwd",""),false).path();ArrayList<String> cmd=new ArrayList<>(List.of("git","-C",cwd.toString()));switch(c.toolId()){case GIT_STATUS->cmd.addAll(List.of("status","--porcelain=v2","--branch"));case GIT_DIFF->{cmd.add("diff");if(bool(a,"staged",false))cmd.add("--cached");cmd.add("--");cmd.addAll(strings(a,"paths"));}case GIT_LOG->cmd.addAll(List.of("log","--oneline","--decorate","--graph","-n",String.valueOf(integer(a,"limit",30,1,200))));case GIT_BRANCHES->cmd.addAll(List.of("branch","--all","--verbose","--no-abbrev"));case GIT_STAGE->{cmd.add("add");List<String> p=strings(a,"paths");cmd.addAll(p.isEmpty()?List.of("."):p);}case GIT_COMMIT->{cmd.addAll(List.of("commit","-m",string(a,"message","")));}case GIT_INSPECT->{String mode=string(a,"mode","merge");String target=string(a,"target","HEAD");if("merge".equals(mode))cmd.addAll(List.of("log","--left-right","--graph","--oneline","HEAD..."+target));else cmd.addAll(List.of("rebase","--show-current-patch"));}}
        var r=WorkspaceProcessService.run(cwd,cmd,System.getenv(),120);JsonObject o=proc(cmd,r);return r.exitCode()==0?completed(c,o,"Git operation completed."):new ModelToolResult(c.id(),c.toolId(),"failed",o,"git_exit_nonzero","Git exited with code "+r.exitCode()+".");}
    private static ModelToolResult archive(ModelToolCall c)throws Exception{JsonObject a=args(c);String ws=string(a,"workspace","project");String format=string(a,"format","auto");return switch(c.toolId()){case ARC_INSPECT->inspectArchive(c,ws,string(a,"path",""),format);case ARC_CREATE->createArchive(c,ws,string(a,"path",""),strings(a,"sources"),format);case ARC_EXTRACT->extractArchive(c,ws,string(a,"path",""),string(a,"destination",""),format);case ARC_COMPARE->compareArchive(c,ws,string(a,"left",""),string(a,"right",""));case ARC_PATCH->patchArchive(c,ws,string(a,"path",""),strings(a,"sources"));default->failed(c,"unknown_archive_tool","Unknown archive capability.");};}
    private static ModelToolResult inspectArchive(ModelToolCall c,String ws,String path,String format)throws Exception{Path p=ModelWorkspaceRegistry.resolve(ws,path,false).path();if(isZip(p,format)){JsonArray e=new JsonArray();try(ZipFile z=new ZipFile(p.toFile())){z.stream().limit(1000).forEach(x->{JsonObject o=new JsonObject();o.addProperty("name",x.getName());o.addProperty("size",x.getSize());o.addProperty("compressedSize",x.getCompressedSize());o.addProperty("directory",x.isDirectory());e.add(o);});}JsonObject out=new JsonObject();out.add("entries",e);out.addProperty("count",e.size());out.addProperty("format","zip");return completed(c,out,"Inspected ZIP archive.");}return tarCommand(c,p.getParent(),List.of("tar","-tf",p.toString()),"Inspected TAR archive.");}
    private static ModelToolResult createArchive(ModelToolCall c,String ws,String path,List<String>src,String format)throws Exception{if(src.isEmpty())return failed(c,"sources_missing","sources is required.");Path dst=ModelWorkspaceRegistry.resolve(ws,path,true).path();if(isZip(dst,format)){try(ZipOutputStream zout=new ZipOutputStream(Files.newOutputStream(dst))){for(String s:src){Path root=ModelWorkspaceRegistry.resolve(ws,s,false).path();Path base=root.getParent();if(Files.isDirectory(root))try(var walk=Files.walk(root)){for(Path f:walk.filter(Files::isRegularFile).toList())addZip(zout,base,f);}else addZip(zout,base,root);}}JsonObject o=new JsonObject();o.addProperty("path",dst.toString());o.addProperty("format","zip");return completed(c,o,"Created ZIP archive.");}ArrayList<String>cmd=new ArrayList<>(List.of("tar","-cf",dst.toString()));cmd.addAll(src);Path root=ModelWorkspaceRegistry.resolve(ws,"",false).path();return tarCommand(c,root,cmd,"Created TAR archive.");}
    private static ModelToolResult extractArchive(ModelToolCall c,String ws,String path,String dest,String format)throws Exception{Path src=ModelWorkspaceRegistry.resolve(ws,path,false).path();Path root=ModelWorkspaceRegistry.resolve(ws,dest,true).path();Files.createDirectories(root);if(isZip(src,format)){try(ZipInputStream zin=new ZipInputStream(Files.newInputStream(src))){ZipEntry e;while((e=zin.getNextEntry())!=null){Path out=root.resolve(e.getName()).normalize();if(!out.startsWith(root))throw new IOException("Archive entry escapes destination: "+e.getName());if(e.isDirectory())Files.createDirectories(out);else{Files.createDirectories(out.getParent());Files.copy(zin,out,StandardCopyOption.REPLACE_EXISTING);}}}JsonObject o=new JsonObject();o.addProperty("destination",root.toString());return completed(c,o,"Extracted ZIP archive safely inside workspace.");}return tarCommand(c,root,List.of("tar","-xf",src.toString(),"-C",root.toString()),"Extracted TAR archive.");}
    private static ModelToolResult compareArchive(ModelToolCall c,String ws,String left,String right)throws Exception{Set<String>a=entryNames(ModelWorkspaceRegistry.resolve(ws,left,false).path()),b=entryNames(ModelWorkspaceRegistry.resolve(ws,right,false).path());JsonArray onlyA=new JsonArray(),onlyB=new JsonArray(),both=new JsonArray();for(String s:a)if(!b.contains(s))onlyA.add(s);else both.add(s);for(String s:b)if(!a.contains(s))onlyB.add(s);JsonObject o=new JsonObject();o.add("onlyLeft",onlyA);o.add("onlyRight",onlyB);o.add("common",both);return completed(c,o,"Compared archive entry sets.");}
    private static ModelToolResult patchArchive(ModelToolCall c,String ws,String path,List<String>src)throws Exception{Path zip=ModelWorkspaceRegistry.resolve(ws,path,false).path();if(!isZip(zip,"auto"))return failed(c,"patch_format_unsupported","archive.patch currently patches ZIP archives; TAR can be extracted, modified, and recreated.");Path temp=Files.createTempDirectory("koil-archive-patch");try{extractZip(zip,temp);for(String s:src){Path from=ModelWorkspaceRegistry.resolve(ws,s,false).path();Path target=temp.resolve(from.getFileName());if(Files.isDirectory(from))copyTree(from,target);else Files.copy(from,target,StandardCopyOption.REPLACE_EXISTING);}Path replacement=Files.createTempFile(zip.getParent(),"koil-patch-",".zip");try(ZipOutputStream zout=new ZipOutputStream(Files.newOutputStream(replacement))){try(var walk=Files.walk(temp)){for(Path f:walk.filter(Files::isRegularFile).toList())addZip(zout,temp,f);}}Files.move(replacement,zip,StandardCopyOption.REPLACE_EXISTING);JsonObject o=new JsonObject();o.addProperty("path",zip.toString());o.addProperty("patchedSources",src.size());return completed(c,o,"Patched ZIP archive.");}finally{deleteTree(temp);}}
    private static void addZip(ZipOutputStream z,Path base,Path f)throws IOException{String name=base.relativize(f).toString().replace('\\','/');z.putNextEntry(new ZipEntry(name));Files.copy(f,z);z.closeEntry();}private static void extractZip(Path zip,Path root)throws IOException{try(ZipInputStream in=new ZipInputStream(Files.newInputStream(zip))){ZipEntry e;while((e=in.getNextEntry())!=null){Path out=root.resolve(e.getName()).normalize();if(!out.startsWith(root))throw new IOException("unsafe zip path");if(e.isDirectory())Files.createDirectories(out);else{Files.createDirectories(out.getParent());Files.copy(in,out,StandardCopyOption.REPLACE_EXISTING);}}}}private static void copyTree(Path from,Path to)throws IOException{try(var w=Files.walk(from)){for(Path p:w.toList()){Path q=to.resolve(from.relativize(p));if(Files.isDirectory(p))Files.createDirectories(q);else{Files.createDirectories(q.getParent());Files.copy(p,q,StandardCopyOption.REPLACE_EXISTING);}}}}private static void deleteTree(Path root)throws IOException{if(Files.exists(root))try(var w=Files.walk(root)){for(Path p:w.sorted(Comparator.reverseOrder()).toList())Files.deleteIfExists(p);}}
    private static Set<String>entryNames(Path p)throws Exception{if(isZip(p,"auto")){HashSet<String>s=new HashSet<>();try(ZipFile z=new ZipFile(p.toFile())){z.stream().forEach(e->s.add(e.getName()));}return s;}var r=WorkspaceProcessService.run(p.getParent(),List.of("tar","-tf",p.toString()),System.getenv(),30);return new HashSet<>(Arrays.asList(r.stdout().split("\\R")));}
    private static boolean isZip(Path p,String f){return"zip".equalsIgnoreCase(f)||("auto".equalsIgnoreCase(f)&&p.getFileName().toString().toLowerCase(Locale.ROOT).endsWith(".zip"));}private static ModelToolResult tarCommand(ModelToolCall c,Path cwd,List<String>cmd,String detail)throws Exception{var r=WorkspaceProcessService.run(cwd,cmd,System.getenv(),120);JsonObject o=proc(cmd,r);return r.exitCode()==0?completed(c,o,detail):new ModelToolResult(c.id(),c.toolId(),"failed",o,"archive_process_failed","Archive command exited with code "+r.exitCode()+".");}
    private static JsonObject proc(List<String>cmd,WorkspaceProcessService.RunResult r){JsonObject o=new JsonObject();JsonArray a=new JsonArray();cmd.forEach(a::add);o.add("argv",a);o.addProperty("stdout",r.stdout());o.addProperty("stderr",r.stderr());o.addProperty("exitCode",r.exitCode());o.addProperty("timedOut",r.timedOut());return o;}
    private static List<ModelToolDefinition>definitions(){List<ModelToolDefinition>t=new ArrayList<>();JsonObject git=object();props(git).add("workspace",str());props(git).add("cwd",str());props(git).add("paths",arrStr());props(git).add("staged",boolSchema());props(git).add("limit",integerSchema(1,200));props(git).add("message",str());props(git).add("mode",enm("merge","rebase"));props(git).add("target",str());for(String id:List.of(GIT_STATUS,GIT_DIFF,GIT_LOG,GIT_BRANCHES,GIT_INSPECT))t.add(read(id,"Structured Git "+id.substring(4)+" inspection without requiring raw shell composition.",git));for(String id:List.of(GIT_STAGE,GIT_COMMIT))t.add(mut(id,"Approved Git mutation for "+id.substring(4)+".",git));JsonObject ar=object();for(String k:List.of("workspace","path","destination","left","right"))props(ar).add(k,str());props(ar).add("sources",arrStr());props(ar).add("format",enm("auto","zip","tar"));t.add(read(ARC_INSPECT,"Inspect ZIP/TAR entries without extracting them.",ar));t.add(read(ARC_COMPARE,"Compare archive entry sets.",ar));for(String id:List.of(ARC_CREATE,ARC_EXTRACT,ARC_PATCH))t.add(mut(id,"Approved archive operation: "+id.substring(8)+".",ar));return List.copyOf(t);}private static ModelToolDefinition read(String id,String d,JsonObject s){return new ModelToolDefinition(id,d,s,List.of("automation_mode_enabled"),Set.of(),false,Duration.ofSeconds(60),true,false,Set.of("completed","failed"),ToolExecutionPolicy.readOnly(ToolExecutionPolicy.FreshnessMode.WORKSPACE,ToolExecutionPolicy.CostClass.MODERATE));}private static ModelToolDefinition mut(String id,String d,JsonObject s){return new ModelToolDefinition(id,d,s,List.of("automation_mode_enabled"),Set.of("workspace_files"),true,Duration.ofMinutes(5),true,true,Set.of("completed","failed"),ToolExecutionPolicy.validateOnlyMutation(ToolExecutionPolicy.CostClass.MODERATE));}
    private static JsonObject object(){JsonObject o=new JsonObject();o.addProperty("type","object");o.addProperty("additionalProperties",false);o.add("properties",new JsonObject());return o;}private static JsonObject props(JsonObject o){return o.getAsJsonObject("properties");}private static JsonObject str(){JsonObject o=new JsonObject();o.addProperty("type","string");return o;}private static JsonObject arrStr(){JsonObject o=new JsonObject();o.addProperty("type","array");o.add("items",str());return o;}private static JsonObject boolSchema(){JsonObject o=new JsonObject();o.addProperty("type","boolean");return o;}private static JsonObject integerSchema(int min,int max){JsonObject o=new JsonObject();o.addProperty("type","integer");o.addProperty("minimum",min);o.addProperty("maximum",max);return o;}private static JsonObject enm(String...v){JsonObject o=str();JsonArray a=new JsonArray();for(String s:v)a.add(s);o.add("enum",a);return o;}private static JsonObject args(ModelToolCall c){return c.arguments()==null?new JsonObject():c.arguments();}private static String string(JsonObject a,String k,String f){return a!=null&&a.has(k)&&!a.get(k).isJsonNull()?a.get(k).getAsString().strip():f;}private static boolean bool(JsonObject a,String k,boolean f){return a!=null&&a.has(k)&&!a.get(k).isJsonNull()?a.get(k).getAsBoolean():f;}private static int integer(JsonObject a,String k,int f,int min,int max){int v=a!=null&&a.has(k)?a.get(k).getAsInt():f;return Math.max(min,Math.min(max,v));}private static List<String>strings(JsonObject a,String k){if(a==null||!a.has(k)||!a.get(k).isJsonArray())return List.of();ArrayList<String>r=new ArrayList<>();a.getAsJsonArray(k).forEach(e->r.add(e.getAsString()));return r;}private static ModelToolResult completed(ModelToolCall c,JsonObject o,String d){return new ModelToolResult(c.id(),c.toolId(),"completed",o,"",d);}private static ModelToolResult failed(ModelToolCall c,String code,String d){return new ModelToolResult(c==null?"":c.id(),c==null?"":c.toolId(),"failed",new JsonObject(),code,d);}private static String msg(Throwable t){return t.getMessage()==null?t.getClass().getSimpleName():t.getMessage();}
}
